version: "3"

services:
  processing-center:
    build: ./processingCenter
    command: npm start
    ports:
      - "3001:3001"
    volumes:
      - ./processingCenter:/usr/app
  sensor:
    build: ./sensor
    command: npm start
    ports:
      - "3002:3002"
    volumes:
      - ./sensor:/usr/app
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:latest"
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
